### ISSUE TITLE
Issues /w login

### ISSUE THREAD

**Issue by shirtsofholl** [jacquesbh/jbh_cartmerge#4]
We are sueing issues after login on Magento 1.9.0.1

* redirect to *random* page?
* customers can no longer login - and there is no error message

**Comment by jacquesbh** [comment]
Are you sure that the module is the cause ?
Le 22 mars 2015 10:16, "shirtsofholland" <notifications@github.com> a
écrit :

**Comment by shirtsofholl** [comment]
No I am not. And after some testing we found out there is a bug in Magento 1.9. Login on Safari does not always work on all devices. The random page however was not solved - but cannot be contributed to this extension.

So to conclude: thanks for your great extension!

**Comment by jacquesbh** [comment]
You're welcome ^^
